
lookup_vri_grp <- function(){
  lookuptable <- data.table(projectID = c("0000","0011","001Y","0021","002Y","0030","0031","0032",
                                          "003Y","0051","005Y","0071","0072","007Y","0081","0082",
                                          "0091","0092","009Y","0101","0102","0111","0112","0113",
                                          "0114","011M","011R","0121","0131","0132","013Y","0141",
                                          "0142","0143","014Y","0151","0161","0171","0172","017Y",
                                          "0191","0201","0202","0203","020Y","0211","0221","0222",
                                          "0223","022M","022P","022R","0231","0232","0241","0242",
                                          "024B","024C","024D","024S","024Y","0251","0252","025Y",
                                          "0261","0262","026M","026Y","0271","0272","027Y","0291",
                                          "0292","029A","029E","029M","0301","0302","0303","0304",
                                          "030Y","0331","0332","0371","037A","0401","0402","0403",
                                          "0411","0461","0471","1111","3011","3031","3051","3052",
                                          "3061","3081","3151","3181","3191","3231","3232","3233",
                                          "3251","3252","3253","3254","325M","332P","3391","3431",
                                          "3432","3433","3434","3471","4561","4571","4701","4721",
                                          "4722","4741","4742","4743","474A","4761","4771","4772",
                                          "477M","477P","4791","4792","5901","BFP1","CAR1","CFP1",
                                          "CFP2","CFP3","CMI1","CMI2","CMI3","CMI4","CMI5","CMI6",
                                          "DAR1","DAR2","DBO1","DCK1","DDC1","DDC2","DDC3","DDCA",
                                          "DDCB","DDCX","DDCY","DDCZ","DEV1","DEV2","DEV3","DEV4",
                                          "DEV5","DEV6","DEV9","DJA1","DKA1","DLL1","DME1","DMEM",
                                          "DMH1","DMH2","DMHA","DMHM","DPG1","DQUE","DSC1","DSC2",
                                          "DVA1","DVA2","INT1","INT2","KAM1","KMHY","KOL1","LGM1",
                                          "LGM2","LGM3","LGM4","LGMA","LGMB","LGMC","LGMD","LGMW",
                                          "LVI1","MMF","MOOS","NCAI","PEN1","PP30","ROM1","TEST",
                                          "TOL3","TST1","TST2","TST4","UBC1","VIL1","VILY","WPVT","YW01"),
                            projectGroup = c("TEST","West Kootenay","West Kootenay","West Kootenay",
                                             "West Kootenay","Fraser North","Bulkley Nadina",
                                             "Bulkley Nadina","Bulkley Nadina","East Kootenay",
                                             "East Kootenay","East Kootenay","East Kootenay",
                                             "East Kootenay","Peace Liard","Peace Liard","East Kootenay",
                                             "East Kootenay","East Kootenay","Skeena","Skeena","Kamloops",
                                             "Kamloops","Kamloops","Kamloops","Kamloops","Kamloops",
                                             "Bulkley Nadina","West Kootenay","West Kootenay",
                                             "West Kootenay","Bulkley Nadina","Bulkley Nadina",
                                             "Bulkley Nadina","Bulkley Nadina","Kamloops","PG_Mackenzie",
                                             "Robson Valley","Robson Valley","Robson Valley","GBR",
                                             "Bulkley Nadina","Bulkley Nadina","Bulkley Nadina",
                                             "Bulkley Nadina","GBR","Okanagan","Okanagan","Okanagan",
                                             "Okanagan","Okanagan","Okanagan","Cariboo","Cariboo",
                                             "PG_Mackenzie","PG_Mackenzie","PG_Mackenzie","PG_Mackenzie",
                                             "PG_Mackenzie","PG_Mackenzie","PG_Mackenzie","Haida Gwaii",
                                             "Haida Gwaii","Haida Gwaii","Cariboo","Cariboo","Cariboo",
                                             "Cariboo","West Kootenay","West Kootenay","West Kootenay",
                                             "Cariboo","Cariboo","Cariboo","Cariboo","Cariboo",
                                             "Fraser South","Fraser South","Fraser South","Fraser South",
                                             "Fraser South","GBR","GBR","Island","Island","Peace Liard",
                                             "Peace Liard","Peace Liard","Peace Liard","GBR","GBR",
                                             "TEST","Skeena","West Kootenay","Cariboo","Cariboo",
                                             "Island","West Kootenay","Kamloops","Kamloops","Island",
                                             "West Kootenay","West Kootenay","West Kootenay",
                                             "PG_Mackenzie","PG_Mackenzie","PG_Mackenzie","PG_Mackenzie",
                                             "PG_Mackenzie","Kamloops","Okanagan","Island","Haida Gwaii",
                                             "Island","Island","Island","GBR","Island","Island",
                                             "Okanagan","Okanagan","Peace Liard","Peace Liard",
                                             "Peace Liard","Peace Liard","PG_Mackenzie","Cariboo",
                                             "Cariboo","Cariboo","Cariboo","West Kootenay",
                                             "West Kootenay","Okanagan","Bulkley Nadina","Cariboo",
                                             "Peace Liard","Peace Liard","Peace Liard","Cariboo",
                                             "Kamloops","West Kootenay","PG_Mackenzie","Bulkley Nadina",
                                             "South Coast","West Kootenay","West Kootenay",
                                             "West Kootenay","Fraser South","Peace Liard","Peace Liard",
                                             "Peace Liard","Peace Liard","Peace Liard","Peace Liard",
                                             "Peace Liard","Peace Liard","TEST","TEST","TEST","TEST",
                                             "TEST","TEST","TEST","PG_Mackenzie","Kamloops","Kamloops",
                                             "Kamloops","Kamloops","Cariboo","Cariboo","Cariboo",
                                             "Cariboo","PG_Mackenzie","Cariboo","South Coast",
                                             "South Coast","PG_Mackenzie","PG_Mackenzie","Okanagan",
                                             "Okanagan","Kamloops","Kamloops","Kamloops","Cariboo",
                                             "Cariboo","Cariboo","Cariboo","Cariboo","Cariboo",
                                             "Cariboo","Cariboo","Cariboo","Cariboo","PG_Mackenzie",
                                             "Robson Valley","Skeena","Okanagan","Fraser North",
                                             "East Kootenay","Okanagan","Okanagan","TEST","TEST",
                                             "TEST","Fraser South","Island","Island","Cariboo",
                                             "Robson Valley"))
  return(lookuptable)
  
}