## Species lookup table
# this is to ensure consistency with the recommended species site index equation mapping in SiteTools ver 4.2.
lookup_species <- function(){
  speciesmatrix <- matrix(ncol = 7,
                          byrow = TRUE,
                          ## SPECIES SP   DESCRIPTION                  SP_SINDEX SP_TYPE SP_COST
                          data = c("A",     "AC", "Cottonwood",                "AT",      "D",     "AC",    "POPULUS",
                                   "AC",    "AC", "Poplar",                    "ACB",     "D",     "AC",    "POPUBAL",
                                   "ACB",   "AC", "Balsam Poplar",             "ACB",     "D",     "AC",    "POPUBAL1",
                                   "ACT",   "AC", "Black Cottonwood",          "ACT",     "D",     "AC",    "POPUBAL2",
                                   "ACT",   "AC", "Black Cottonwood",          "ACT",     "D",     "AC",    "POPUTRI",
                                   "AD",    "AC", "Southern Cottonwood",       "ACT",     "D",     "AC",    "POPUDEL1",
                                   "AD",    "AC", "Southern Cottonwood",       "ACT",     "D",     "AC",    "POPUDEL",
                                   "AH",    "AC", "Poplar Cottonwood/HYBD",    "ACT",     "D",     "AC",    NA,
                                   "AT",    "AT", "Trembling Aspen",           "AT",      "D",     "AC",    "POPUTRE",
                                   "AX",    "AC", "Hybrid Poplar",             "ACB",     "D",     "AC",    "POPULX",
                                   "B",     "B",  "Balsam",                    "BA",      "C",     "B",     "ABIES",
                                   "BA",    "B",  "Amabalis Fir",              "BA",      "C",     "B",     "ABIEAMA",
                                   "BB",    "B",  "Balsam Fir",                "BL",      "C",     "B",     "ABIEBAL",
                                   "BC",    "B",  "White Fir",                 "BA",      "C",     "B",     "ABIECON",
                                   "BG",    "B",  "Grand Fir",                 "BA",      "C",     "B",     "ABIEGRA",
                                   "BL",    "B",  "Subalpine Fir",             "BL",      "C",     "B",     "ABIELAS",
                                   "BM",    "B",  "Shasta Red Fir",            "BA",      "C",     "B",     "ABIEMAG1",
                                   "BP",    "B",  "Noble Fir",                 "BP",      "C",     "B",     "ABIEPRO",
                                   "C",     "C",  "Cedar",                     "CW",      "C",     "C",     "THUJA",
                                   "CI",    "C",  "Incense Cedar",             "CW",      "C",     "C",     NA,
                                   "CP",    "C",  "Port-Orford Cedar",         "CW",      "C",     "Y",     NA,
                                   "CW",    "C",  "Western Red Cedar",         "CW",      "C",     "C",     "THUJPLI",
                                   "CY",    "Y",  "Yellow Cedar",              "CW",      "C",     "Y",     NA,
                                   "D",     "D",  "Alder",                     "DR",      "D",     "D",     "ALNUS",
                                   "DG",    "D",  "Sitka Alder",               "DR",      "D",     "D",     NA,
                                   "DM",    "D",  "Mountain Alder",            "DR",      "D",     "D",     "ALNUTEN",
                                   "DR",    "D",  "Red Alder",                 "DR",      "D",     "D",     "ALNURUB",
                                   "DS",    "D",  "Sitka Alder",               "DR",      "D",     "D",     NA,
                                   "E",     "E",  "Birch",                     "AT",      "D",     "D",     "BETULA",
                                   "EA",    "E",  "Alaska Paper Birch",        "AT",      "D",     "D",     "BETUNEO",
                                   "EB",    "E",  "Scrub Birch",               "AT",      "D",     "D",     NA,
                                   "EE",    "E",  "European birch",            "AT",      "D",     "D",     "BETUPEN",
                                   "EP",    "E",  "Paper Birch",               "EP",      "D",     "D",     "BETUPAP",
                                   "ES",    "E",  "Silver birch",              "AT",      "D",     "D",     "BETUPUB",
                                   "EW",    "E",  "Water Birch",               "AT",      "D",     "D",     "BETUOCC",
                                   "EXP",   "E",  "Alaska x paper birch hybr", "AT",      "D",     "D",     "BETUXWI",
                                   "EY",    "E",  "Yellow Birch",              "AT",      "D",     "D",     "BETUALL",
                                   "F",     "F",  "Douglas-Fir",               "FD",      "C",     "F",     "PSEUDOT",
                                   "FD",    "F",  "Douglas-Fir",               "FD",      "C",     "F",     "PSEUMEN",
                                   "FDC",   "F",  "Coastal Douglas-fir",       "FDC",     "C",     "F",     "PSEUMEN2",
                                   "FDI",   "F",  "Interior Douglas-fir",      "FDI",     "C",     "F",     "PSEUMEN1",
                                   "G",     "MB", "Dogwood",                   "DR",      "D",     "D",     "CORNUS",
                                   "GP",    "MB", "Pacific Dogwood",           "DR",      "D",     "D",     "CORNNUT",
                                   "H",     "H",  "Hemlock",                   "HW",      "C",     "H",     "TSUGA",
                                   "HM",    "H",  "Mountain Hemlock",          "HM",     "C",     "H",     "TSUGMER",
                                   "HW",    "H",  "Western Hemlock",           "HW",      "C",     "H",     "TSUGHET",
                                   "HXM",   "H",  "Mtn * Wstrn Hemlock Hybri", "HWC",     "C",     "H",     "TSUGHEE",
                                   "IG",    "C",  "Giant Sequoia",             "CW",      "C",     "C",     NA,
                                   "IS",    "C",  "Coast Redwood",             "CW",      "C",     "C",     NA,
                                   "J",     "C",  "Juniper",                   "CW",      "C",     "C",     "JUNIPER",
                                   "JR",    "C",  "Rocky Mtn. Juniper",        "CW",      "C",     "C",     "JUNISCO",
                                   "K",     "E",  "Cascara",                   "AT",      "D",     "D",     "RHAMNUS",
                                   "KC",    "E",  "Cascara",                   "AT",      "D",     "D",     "RHAMPUR",
                                   "L",     "L",  "Larch",                     "LW",      "C",     "F",     "LARIX",
                                   "LA",    "L",  "Alpine Larch",              "LW",      "C",     "F",     "LARILYA",
                                   "LD",    "L",  "Dahurian (Bob's) Larch",    "LW",      "C",     "F",     "LARIGME",
                                   "LE",    "L",  "Eastern Larch",             "LW",      "C",     "F",     NA,
                                   "LT",    "L",  "Tamarak",                   "LW",      "C",     "F",     "LARILAR",
                                   "LW",    "L",  "Western Larch",             "LW",      "C",     "F",     "LARIOCC",
                                   "M",     "MB", "Maple",                     "DR",      "D",     "M",     "ACER",
                                   "MB",    "MB", "Bigleaf Maple",             "DR",      "D",     "M",     "ACERMAC",
                                   "ME",    "E",  "Box Elder",                 "DR",      "D",     "M",     "ACERNEG",
                                   "MN",    "MB", "Norway maple",              "DR",      "D",     "M",     "ACERPLA",
                                   "MR",    "MB", "Douglas Maple",             "DR",      "D",     "M",     NA,
                                   "MS",    "MB", "Sycamore maple",            "DR",      "D",     "M",     "ACERPSE",
                                   "MV",    "MB", "Vine Maple",                "DR",      "D",     "M",     "ACERCIR",
                                   "OA",    "C",  "Incense-cedar",             "CW",      "C",     "C",     "CALODEC",
                                   "OB",    "C",  "Giant sequoia",             "CW",      "C",     "C",     "SEQUGIG",
                                   "OC",    "C",  "Coast redwood",             "CW",      "C",     "C",     "SEQUSEM",
                                   "OD",    "MB", "European mountain-ash",     "AT",      "D",     "D",     "SORBAUC",
                                   "OE",    "MB", "Siberian elm",              "AT",      "D",     "D",     "ULMUPUM",
                                   "OF",    "MB", "common pear",               "AT",      "D",     "D",     "PYRUCOM",
                                   "OG",    "MB", "Oregon ash",                "AT",      "D",     "D",     "FRAXLAT",
                                   "OH",    "MB", "White Ash",                 "AT",      "D",     "D",     "FRAXAME",
                                   "OI",    "MB", "Shagbark Hickory",          "AT",      "D",     "D",     "CARYOVA",
                                   "P",     "PL", "Pine",                      "PL",      "C",     "P",     "PINUS",
                                   "PA",    "PA", "Whitebark Pine",            "PL",      "C",     "P",     "PINUALB",
                                   "PF",    "PW", "Limber Pine",               "PL",      "C",     "P",     "PINUFLE",
                                   "PJ",    "PL", "Jack Pine",                 "PL",      "C",     "P",     "PINUBAN",
                                   "PL",    "PL", "Lodgepole Pine",            "PL",      "C",     "P",     "PINUCON",
                                   "PLC",   "PL", "Shore Pine",                "PL",      "C",     "P",     "PINUCON1",
                                   "PLI",   "PL", "Lodgepole Pine Interior",   "PL",      "C",     "P",     "PINUCON2",
                                   "PM",    "PW", "Monterey Pine",             "PL",      "C",     "P",     "PINURAD",
                                   "PR",    "PW", "Red Pine",                  "PL",      "C",     "P",     "PINURES",
                                   "PS",    "PW", "Sugar Pine",                "PL",      "C",     "P",     "PINULAM",
                                   "PW",    "PW", "Western White Pine",        "PW",      "C",     "P",     "PINUMON",
                                   "PXJ",   "PL", "Lodgepole x Jack Pine",     "PL",      "C",     "P",     "PINUXMU",
                                   "PY",    "PY", "Ponderosa Pine",            "PY",      "C",     "P",     "PINUPON",
                                   "Q",     "MB", "Oak",                       "AT",      "D",     "D",     "QUERCUS",
                                   "QE",    "MB", "English oak",               "AT",      "D",     "D",     "QUERROB",
                                   "QG",    "MB", ", Garry Oak",                "AT",      "D",     "D",     "QUERGAR",
                                   "QW",    "MB", "White Oak",                 "AT",      "D",     "D",     "QUERALB",
                                   "R",     "MB", "Arbutus",                   "DR",      "D",     "D",     "ARBUTUS",
                                   "RA",    "MB", "Arbutus",                   "DR",      "D",     "D",     "ARBUMEN",
                                   "S",     "S",  "Spruce",                    "S",       "C",     "S",     "PICEA",
                                   "SA",    "S",  "Norway Spruce",             "SW",      "C",     "S",     NA,
                                   "SB",    "S",  "Black Spruce",              "SB",      "C",     "S",     "PICEMAR",
                                   "SE",    "S",  "Engelmann Spruce",          "SE",      "C",     "S",     "PICEENG",
                                   "SN",    "S",  "Norway spruce",             "SW",      "C",     "S",     "PICEABI",
                                   "SS",    "S",  "Sitka Spruce",              "SS",      "C",     "S",     "PICESIT",
                                   "SW",    "S",  "White Spruce",              "SW",      "C",     "S",     "PICEGLA",
                                   "SX",    "S",  "Spruce Hybrid",             "SW",      "C",     "S",     "PICEAX",
                                   "SXB",   "S",  "Spruce glauca * mariana",   "SW",      "C",     "S",     "PICEGLM",
                                   "SXE",   "S",  "Sitka X Engleman Spruce",   "SS",      "C",     "S",     "PICEENS",
                                   "SXL",   "S",  "Sitka x White Spruce",      "SS",      "C",     "S",     "PICEXLU",
                                   "SXS",   "S",  "Sitka & Unknown Spruce",    "SS",      "C",     "S",     "PICESIX",
                                   "SXW",   "S",  "White x Engelmann Spruce",  "SW",      "C",     "S",     "PICEENE",
                                   "SXX",   "S",  "Spruce glauca x engelmann", "SW",      "C",     "S",     "PICEGES",
                                   "T",     "H",  "Yew",                       "HWC",     "C",     "Y",     "TAXUS",
                                   "TW",    "H",  "Pacific Yew",               "HWC",     "C",     "Y",     "TAXUBRE",
                                   "U",     "E",  "Apple",                     "AT",      "D",     "D",     "MALUS",
                                   "UA",    "E",  "apple",                     "AT",      "D",     "D",     "MALUPUM",
                                   "UP",    "E",  "Pacific crab apple",        "AT",      "D",     "D",     "MALUFUS",
                                   "V",     "E",  "Cherry",                    "AT",      "D",     "D",     "PRUNUS",
                                   "VB",    "E",  "Bitter Cherry",             "AT",      "D",     "D",     "PRUNEMA",
                                   "VP",    "E",  "Pin Cherry",                "AT",      "D",     "D",     "PRUNPEN",
                                   "VS",    "E",  "sweet cherry",              "AT",      "D",     "D",     "PRUNAVI",
                                   "VV",    "E",  "Choke Cherry",              "AT",      "D",     "D",     "PRUNVIR",
                                   "W",     "E",  "Willow",                    "AT",      "D",     "D",     "SALIX",
                                   "WA",    "E",  "Peachleaf willow",          "AT",      "D",     "D",     "SALIAMY",
                                   "WB",    "E",  "Bebb's willow",             "AT",      "D",     "D",     "SALIBEB",
                                   "WD",    "E",  "pussy willow",              "AT",      "D",     "D",     "SALIDIS",
                                   "WP",    "E",  "Pacific willow",            "AT",      "D",     "D",     "SALILUC2",
                                   "WP",    "E",  "Pacific willow",            "AT",      "D",     "D",     "SALILUC",
                                   "WS",    "E",  "Scouler's willow",          "AT",      "D",     "D",     "SALISCO",
                                   "WT",    "E",  "Sitka willow",              "AT",      "D",     "D",     "SALISIT",
                                   "X",     "F",  "Unknown tree",              "FD",      "C",     "B",     NA,
                                   "XC",    "F",  "Unknown Conifer",           "FD",      "C",     "B",     NA,
                                   "XH",    "E",  "Unknown Hardwood",          "AT",      "D",     "D",     NA,
                                   "Y",     "Y",  "Cypress",                   "CW",      "C",     "Y",     "CHAMAEC",
                                   "YC",    "Y",  "Yellow Cedar",              "CW",      "C",     "Y",     "CHAMNOO",
                                   "YP",    "Y",  "Port Orford-cedar",         "CW",      "C",     "Y",     "CHAMLAW",
                                   "Z",     "E",  "Other tree, not on list",   "FD",      "D",     "B",     NA,
                                   "ZC",    "F",  "Other Conifer",             "FD",      "C",     "B",     NA,
                                   "ZH",    "E",  "Other Hardwood",            "AT",      "D",     "AC",    NA))
  speciestable <- data.table::as.data.table(as.data.frame(speciesmatrix))
  names(speciestable) <- c("SPECIES", "SP0", "DESCRIPTION", "SP_SINDEX", "SP_TYPE", "SP_COST", "LONG_SPECIES")
  speciestable[,':='(SPECIES = as.character(SPECIES),
                     SP0 = as.character(SP0),
                     DESCRIPTION = as.character(DESCRIPTION),
                     SP_SINDEX = as.character(SP_SINDEX),
                     SP_TYPE = as.character(SP_TYPE),
                     SP_COST = as.character(SP_COST),
                     LONG_SPECIES = as.character(LONG_SPECIES))]

  return(speciestable)
}
